### ISSUE TITLE
No way to get ordered data from CRUD/CRUDService

### ISSUE THREAD

**Issue by mortenn** [Kruithne/KrameWork#109]
As has been pointed out in the past, this is lacking.
I have currently ran into a need for this myself and plan to look into this soon.

**Comment by mortenn** [comment]
@Kruithne please assign this issue to me.

**Comment by Kruithne** [comment]
It's not letting me assign you, for whatever reason.

**Comment by mortenn** [comment]
I guess github requires assignee to be part of the team..
