### ISSUE TITLE
Database Improvements

### ISSUE THREAD

**Issue by Kruithne** [Kruithne/KrameWork#45]
@mortenn Spent the night testing all your fancy database stuff and compiled my thoughts below on what I think should be done! Feel free to counter my suggestions. :D

- I would prefer if we didn't have to cast arrays to objects when passing them to KW_CRUD->create();
- A fair chunk of the CRUD code is missing valid PHPDoc which is an important thing for KrameWork to have.
- In crud_example/database_example.php, you reference 'rowid' but it's not created with the initial 'CREATE TABLE' query as a column. Not sure if I am missing something but this seems to throw a spanner in the works.
- Setting hasAutoKey() to true and providing a valid column name from getKey() causes "SQLSTATE[HY093]: Invalid parameter number: no parameters were bound" to be thrown with MySQL.

**Comment by Kruithne** [comment]
Line -> 149
File -> /home/kruithne/nevirra.kruithne.net/KrameWork/KrameWork/KW_CRUD.php
Error -> Undefined property: stdClass::$id

Ran into this a few times when inserting, too.

**Comment by mortenn** [comment]
You shouldn't cast arrays to objects, you should have proper classes.. I just use that method to quickly make an anonymous class in tests/examples.

**Comment by mortenn** [comment]
rowid is a magically appearing automatic row id in sqlite

**Comment by mortenn** [comment]
Could I have a stack trace for that SQLSTATE exception, please?

**Comment by Kruithne** [comment]
Time -> Sunday 17th of January 2016 07:34:33 PM
Type -> EXCEPTION
Line -> 56
File -> /home/kruithne/nevirra.kruithne.net/KrameWork/KrameWork/KW_DatabaseConnection.php
Error -> SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key
Backtrace: In function PDO->exec at /home/kruithne/nevirra.kruithne.net/KrameWork/KrameWork/KW_DatabaseConnection.php:56
In function KW_DatabaseConnection->execute at /home/kruithne/nevirra.kruithne.net/KrameWork/KrameWork/KW_SchemaManager.php:80
In function KW_SchemaManager->upgrade at /home/kruithne/nevirra.kruithne.net/KrameWork/KrameWork/KW_SchemaManager.php:53
In function KW_SchemaManager->update at /home/kruithne/nevirra.kruithne.net/engine/DB.php:13
In function DB::get at /home/kruithne/nevirra.kruithne.net/www/test.php:4

PHP Version -> 5.6.10
Server OS -> Linux


SESSION:
__client__ -> 86.31.52.26
IS_ADMIN -> 1


GET:
No data inside array.


POST:
No data inside array.

**Comment by Kruithne** [comment]
Time -> Sunday 17th of January 2016 07:39:22 PM
Type -> UNKNOWN
Line -> 149
File -> /home/kruithne/nevirra.kruithne.net/KrameWork/KrameWork/KW_CRUD.php
Error -> Undefined property: stdClass::$id
Backtrace: In function KW_ErrorHandler->handleError at /home/kruithne/nevirra.kruithne.net/KrameWork/KrameWork/KW_CRUD.php:149
In function KW_CRUD->bindValues at /home/kruithne/nevirra.kruithne.net/KrameWork/KrameWork/KW_CRUD.php:142
In function KW_CRUD->bind at /home/kruithne/nevirra.kruithne.net/KrameWork/KrameWork/KW_CRUD.php:43
In function KW_CRUD->create at /home/kruithne/nevirra.kruithne.net/www/test.php:13

PHP Version -> 5.6.10
Server OS -> Linux


SESSION:
__client__ -> 86.31.52.26
IS_ADMIN -> 1


GET:
No data inside array.


POST:
No data inside array.

**Comment by mortenn** [comment]
The second stack goes through KW_CRUD->bind, which only happens if hasAutoKey() returns false, see https://github.com/Kruithne/KrameWork/blob/master/KrameWork/KW_CRUD.php#L41

**Comment by mortenn** [comment]
Is this closed now?

**Comment by Kruithne** [comment]
It is now!
