### ISSUE TITLE
Clean-up time.

### ISSUE THREAD

**Issue by Kruithne** [Kruithne/KrameWork#58]
As mentioned on Discord, the framework was in need of some solid guidelines and clean-up! I've refactored a lot of code in an effort to bring things up to speed however there are some portions of code written by yourself (@mortenn) which I would like you to review and correct. :)

These corrections should be commit to the `cleanup` branch!

**KW_AuthenticationService**

Missing phpDoc on `process()`, `authenticate()`, `get_session()`, `use_token()`, `grant_token()`, `token_validate()`, `ip_lock()` and `end_session()`.

@33 - `recover()` does not exist in `IUserSystem`.
@133 - `multifactor` is not defined in `KW_AuthenticationService`.
@150, @162, @165 - `getAuthToken()` cannot be resolved, result of missing phpDoc.

Why do we have hard-coded references to the `runsafe.no` servers in the framework? Not overly sure what this class actually does, a crash-course would be appreciated as skim-reading makes it seem to specific for the framework.

**KW_CacheStateTable**

Missing phpDoc on `clear()`, `read()`, `prepare()`, `getName()`, `getVersion()` and `getQueries()`.

**KW_CRUDCache**

Missing phpDoc on `create()`, `update()`, `delete()`, `cache_clear()` and `cache_read()`.

@41 - Calling method `read()` which is flagged as `@internal`.

**KW_DatabaseStatement**

`__set` is using `:` as a hard-coded prepend character. Shouldn't this be optional like in older methods such as `copyValuesFromRow()`? I don't really see people changing it, but it makes sense to either have it optional everywhere, or nowhere.

**KW_DataContainer**

Missing phpDoc on `serialize()` and `unserialize()`. Import from base class or?

**KW_DeferredStatement**

Missing phpDoc for `getQueryString()`, `setValue()`, `setType()`, `__set()`, `copyValuesFromRow()`, `execute()`, `getRows()`, `getFirstRow()`, `getRowCount()`, `getErrorCode()` and `prepare()`.

**KW_DependencyInjector**

Missing phpDoc for `addBinding()`, `addDecorator()`, $bindings and $decorators.

**KW_JSONService**

Missing phpDoc for `execute()` and `process()`.

**KW_MetaTable**

Missing phpDoc for `prepare()`, `getName()`, `getVersion()` and `getQueries()`.

**KW_MultifactorService**

Missing phpDoc for `process()`.

@26 - Return statement doesn't return anything when expected.
@92 - `process()` has no default return value.

**KW_QueryBuilder**

I've included phpDoc for `__construct()` however it needs filling out some more.

Missing phpDoc for `build()`, `bind()`, `andColumn()`, `orColumn()`, `like()`, `notLike()`, `isNull()`, `notNull()`, `lessThan()`, `greaterThan()`, `equals()`, `between()`, `execute()`, $glue, $column, $format, $value and $anchor.

@17 - `crud` is assigned, but isn't actually a defined variable in the class which leads to IDE issues for all referneces to `$this->crud` in the class.

**KW_UserSystem**

Missing phpDoc for `prepare()`, `getNewObject()`, `setLoginSuccess()`, `setLoginFailed()`, `lockout()`, `setSessionSalt()`, `setSecret()`, `setPassphrase()`, `getUser()`, `getUsers()`, `addUser()`, `saveUser()`, `getVersion()`, `getQueries()`, `authenticate()`, `getState()`, `encode()`, `verify()`, `hash()` and `getAlgorithm()`.

@89 - Inspection reports `$result` may not have been defined.
@91 - No default return path for `getUser()`.

**Comment by mortenn** [comment]
The runsafe.no references are just a matter of me migrating code from runsafe into the framework and forgetting to generalize those parts
