### ISSUE TITLE
Scalar type hinting == PHP 7

### ISSUE THREAD

**Issue by Kruithne** [Kruithne/KrameWork#72]
@mortenn Noticed that in `IManyInject` we're using scalar type hinting to work around 'type hinting deficiencies'. Apparently this is PHP 7+ only, that's not going to cause a problem is it? It's throwing errors in PHPStorm.

**Comment by Kruithne** [comment]
Same error obviously shows up in `KW_DependencyInjector` where we implement the `getComponents()` method.

**Comment by mortenn** [comment]
Not entirely sure what you mean

**Comment by Kruithne** [comment]
https://wiki.php.net/rfc/scalar_type_hints

Scalar type hints (string, int, bool etc) are only available in PHP 7 and above. KrameWork aims to provide support for 5.4 and up.
